### ISSUE TITLE
cannot find module 'views/home.js' ...

### ISSUE THREAD

**Issue by freder** [keystonejs/keystone#1411]
after switching from `0.3.8` to `0.3.9` I get the following messages:

```
------------------------------------------------
KeystoneJS Started:
project is ready on port 3000
------------------------------------------------

2015-05-18 15:05 error building views/home.js:
Cannot find module 'views/home.js' from '/Volumes/Macintosh HD 2/Projects/project/platform/node_modules/keystone/admin/src'
2015-05-18 15:05 error building views/item.js:
Cannot find module 'views/item.js' from '/Volumes/Macintosh HD 2/Projects/project/platform/node_modules/keystone/admin/src'
2015-05-18 15:05 error building views/list.js:
Cannot find module 'views/list.js' from '/Volumes/Macintosh HD 2/Projects/project/platform/node_modules/keystone/admin/src'
```

**Comment by poksme** [comment]
I get the same messages when trying to access the admin.

**Comment by JedWatson** [comment]
Can you see if the file actually exists? I've just tried a fresh install from npm (via the `yo keystone` generator) and I can't reproduce the issue.

Also try `rm -rf node_modules && npm install` - this may fix it for you

**Comment by poksme** [comment]
Yes the 3 files exists. I tried removing the node_modules directory and run npm install again but it did not fix it.

**Comment by BerkeleyTrue** [comment]
@JedWatson running into the same issue in 0.3.9 on fresh install from npm. The files do exist in the directory.

**Comment by BerkeleyTrue** [comment]
issue disappears when reverting back to 0.3.8

**Comment by JedWatson** [comment]
What platform are you folks using? Because I would love to fix this, but can't until I can reproduce it.

Otherwise could someone who _can_ reproduce it please debug it a bit further?

**Comment by BerkeleyTrue** [comment]
OSX 10.10.3
io.js 1.6.4

**Comment by freder** [comment]
OS X 10.10.3
node 0.12.2

**Comment by freder** [comment]
well, in `admin/app/static.js` changing

```javascript
var bundles = {
	fields: browserify('fields.js', 'FieldTypes'),
	home: browserify('views/home.js'),
	item: browserify('views/item.js'),
	list: browserify('views/list.js')
};
```

to

```javascript
var bundles = {
	fields: browserify('fields.js', 'FieldTypes'),
	home: browserify('../src/views/home.js'),
	item: browserify('../src/views/item.js'),
	list: browserify('../src/views/list.js')
};
```

did it for me.

**Comment by poksme** [comment]
Freder's fix works for me too. Thank you!

Just to be thorough: 
- OS X 10.9.5
- node 0.10.32

**Comment by JedWatson** [comment]
@freder @poksme that is _really_ weird. It seems to be some incompatibility with the way browserify is resolving the path when those files are required.

What's also strange is I'm on OS X 10.10.3 with Node 0.12.2 (and so is @jossmac who can't reproduce the issue either)

I've pushed a change to master that uses node's `path` to resolve the full path to the file, would you mind trying that and letting me know if it works for you?

**Comment by creynders** [comment]
Yeps, got the same problem. Mac OS X 10.10.3

My setup has one major difference with the `yo`d one: I've moved everything into a `app` directory. And run e.g. `nodemon app/keystone.js`
How 'bout you @poksme @freder @BerkeleyTrue ?

**Comment by creynders** [comment]
Will install from `master` to see what happens.

**Comment by creynders** [comment]
Think I found it: 

>`opts.basedir` is the directory that browserify starts bundling from for filenames that start with `.`

I.e. I think it should be 

```js
var bundles = {
	fields: browserify('./fields.js', 'FieldTypes'),
	home: browserify('./views/home.js'),
	item: browserify('./views/item.js'),
	list: browserify('./views/list.js')
};
```

**Comment by JedWatson** [comment]
@creynders that was being prepended in `admin/app/browserify.js`:

```
b.require('./' + file, { expose: name });
```

(previous, breaking version shown)

so that would be the same as the code you've included above.

**Comment by creynders** [comment]
@JedWatson No, it's only being prepended when a name is given, which is not the case for `views/home.js` et cetera.:

```js
		if (name) {
			b = browserify(opts);
			b.require('./' + file, { expose: name });
		} else {
			console.log("file", file);
			b = browserify(file, opts);
		}
```

`console.log`'s mine

**Comment by poksme** [comment]
@creynders your fix works for me too!

@JedWatson I haven't tried the changes you pushed to master yet (keeping up the pace with you guys is hard)

**Comment by JedWatson** [comment]
OH @creynders ffs I am going blind. Fix incoming. @poksme give me a minute :)

**Comment by creynders** [comment]
Been staring at your golden apple watch too much @JedWatson :wink:

**Comment by JedWatson** [comment]
@creynders IT IS NOT GOLD

... also I pushed that change, @poksme @freder @BerkeleyTrue it should be fixed now.

**Comment by freder** [comment]
thanks, you guys!

**Comment by creynders** [comment]
@JedWatson fixed it for me! Still curious why it didn't fail for you guys though...

**Comment by poksme** [comment]
@JedWatson @creynders fixed it for me too, thank you guys!

**Comment by JedWatson** [comment]
I'm curious why the first version worked somewhere and not everywhere. So strange. Weirdest bug I've fixed without actually being able to replicate it.

Glad it works though! Thanks everyone for your patience and help getting it done. I'm going to push out a new release with this in it, hold tight...

**Comment by dcousens** [comment]
@JedWatson please close if this is fixed.

**Comment by creynders** [comment]
Closing this, I can confirm it's fixed in `master`

**Comment by kfancy** [comment]
Hi Team KJS

I'm still encountering this error, it seems browserify is not properly transforming the JSX inside home.js, list.js, view.js, per freezer's original comment on this thread.

Problem appears to be that browserify is not properly transforming the files using jsx (reactify). The unexpected token is the inline jsx <Components />.

> Applying update 0.0.1-admins...
> 2015-07-22 11:07:84 error building views/item.js:
> /Users/______/Code/package.json: Unexpected token < while parsing file: /Users/______/Code/my-app/node_modules/keystone/admin/src/views/item.js
> 2015-07-22 11:07:85 error building fields.js:
> /Users/______/Code/package.json: Unexpected token < while parsing file: /Users/______/Code/my-app/node_modules/keystone/admin/src/fields.js
> 2015-07-22 11:07:86 error building views/home.js:
> /Users/______/Code/package.json: Unexpected token < while parsing file: /Users/______/Code/my-app/node_modules/keystone/admin/src/views/home.js
> 2015-07-22 11:07:86 error building views/list.js:
> /Users/______/Code/package.json: Unexpected token < while parsing file: /Users/______/Code/my-app/node_modules/keystone/admin/src/views/list.js
