### ISSUE TITLE
0.4: Error: Only qualified hooks are allowed, e.g. "pre:save", not "save"

### ISSUE THREAD

**Issue by yn5** [keystonejs/keystone#2072]
I get the following error requesting the admin UI (/keystone) on current master (95c1cf3d6640022506a52f771d1e18e4740c13ef):

```Javascript
Error thrown for request: /keystone/
Error: Only qualified hooks are allowed, e.g. "pre:save", not "save"
    at qualifyHook (/Users/yn5/stuff/web/puha/keystone/node_modules/grappling-hook/index.js:275:9)
    at methods.getMiddleware (/Users/yn5/stuff/web/puha/keystone/node_modules/grappling-hook/index.js:647:3)
    at /Users/yn5/stuff/web/puha/keystone/node_modules/grappling-hook/index.js:585:49
    at dezalgofy (/Users/yn5/stuff/web/puha/keystone/node_modules/grappling-hook/index.js:192:2)
    at methods.callHook (/Users/yn5/stuff/web/puha/keystone/node_modules/grappling-hook/index.js:584:4)
    at /Users/yn5/stuff/web/puha/keystone/server/createApp.js:70:12
    at Layer.handle [as handle_request] (/Users/yn5/stuff/web/puha/keystone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yn5/stuff/web/puha/keystone/node_modules/express/lib/router/index.js:312:13)
    at /Users/yn5/stuff/web/puha/keystone/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/yn5/stuff/web/puha/keystone/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/yn5/stuff/web/puha/keystone/node_modules/express/lib/router/index.js:271:10)
    at logger (/Users/yn5/stuff/web/puha/keystone/node_modules/morgan/index.js:144:5)
    at Layer.handle [as handle_request] (/Users/yn5/stuff/web/puha/keystone/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yn5/stuff/web/puha/keystone/node_modules/express/lib/router/index.js:312:13)
    at /Users/yn5/stuff/web/puha/keystone/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/yn5/stuff/web/puha/keystone/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/yn5/stuff/web/puha/keystone/node_modules/express/lib/router/index.js:271:10)
    at /Users/yn5/stuff/web/puha/keystone/lib/session.js:179:4
    at /Users/yn5/stuff/web/puha/keystone/lib/session.js:56:3
    at Immediate._onImmediate (/Users/yn5/stuff/web/puha/keystone/node_modules/express-session/session/store.js:43:5)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by creynders** [comment]
What exactly happens at /Users/yn5/stuff/web/puha/keystone/server/createApp.js:70:12 ?
Seems to me you're adding hook middleware there to an non-existing hook.

**Comment by wuhaixing** [comment]
createApp.js callHook logger at 70:12

    app.use(function(req, res, next) {
	    keystone.callHook('logger', req, res, next);
    });

**Comment by creynders** [comment]
Here's the culprit then: https://github.com/keystonejs/keystone/commit/afc3384e8cb6e73cc2ce24c8178eb4f6e001ebc0#diff-9f4c53deca522d8a2d2cdda3b980689eR70

Ping: @JedWatson @gmmeyer 

As the error says `callHook` expects a qualified hook, i.e. `logger` is not enough. Is this something we _do_ want though, unqualified hooks? I.e. basically events?

**Comment by edoardo849** [comment]
+1

**Comment by gmmeyer** [comment]
Hmm, my mistake. I must have made a mistake when I tested it. I do think this middleware is a good idea.

**Comment by gmmeyer** [comment]
Sorry!

**Comment by JedWatson** [comment]
Fixed by #2078 and #2079

**Comment by ericelliott** [comment]
Did you mean to close this?

**Comment by yn5** [comment]
Thanks @JedWatson and @gmmeyer.

**Comment by ericelliott** [comment]
Sorry.. still getting this error. Verifying that I'm checking against latest master right now. I'll close again if it goes away. =)

**Comment by ericelliott** [comment]
It went away. Looks like I just needed to clear my dependency cache. Thanks everybody!
