### ISSUE TITLE
[Admin UI]OneToMany field relate didn't work when login in AdminUI

### ISSUE THREAD

**Issue by HackerYunen** [keystonejs/keystone#2553]
# Bug report

## Describe the bug

For example:
User List:
```
keystone.createList('User', {
  label: 'User',
  fields: {
    name: {
      type: Text,
      isUnique: true
    },
    email: {
      type: Text,
    },
    password: {
      type: Password
    },
    userGroup: {
      type: Relationship,
      ref: "Group.users"
    }
  },
});
```
UserGroup List:
```
keystone.createList('Group', {
  label: 'UserGroup',
  fields: {
    name: {
      type: Text,
      isUnique: true
    },
    users: {
      type: Relationship,
      ref: "User.userGroup",
      many: true,
    },
    enableSystem: {
      type: Checkbox
    },
});
```
authStrategy:
```
const authStrategy = keystone.createAuthStrategy({
  type: PasswordAuthStrategy,
  list: 'User',
});
```
AdminUI app:
```
    new AdminUIApp({
      authStrategy,
      isAccessAllowed: ({
        authentication: {
          item: user,
          listKey: list
        }
      }) => !!user && !!user.userGroup.enableSystem
    })
```
Error:
```
TypeError: Cannot read property 'enableSystem' of undefined
    at AdminUIApp.isAccessAllowed [as _isAccessAllowed] (/test/index.js:480:40)
    at AdminUIApp.isAccessAllowed (/test/node_modules/@keystonejs/app-admin-ui/index.js:69:12)
    at app.use (/test/node_modules/@keystonejs/app-admin-ui/index.js:201:23)
    at Layer.handle [as handle_request] (/test/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/test/node_modules/express/lib/router/index.js:317:13)
    at /rat query (/test/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/test/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/topdocs/test/node_modules/express/lib/router/index.js:317:13)
    at /root/topdocs/test/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/test/node_modules/express/lib/router/index.js:335:12)
    at next (/test/node_modules/express/lib/router/index.js:275:10)
```

## To Reproduce

open in browser

## Expected behaviour

It can work.

## System information

- OS: Windows
- Browser Chrome

## Additional context

For avoid this bug, I have to add isAdmin field in User list :(

**Comment by Vultraz** [comment]
Did you ensure your `User` entry in the database actually has a group set? If you created a User (such as with the Starter project template), then added the `userGroup` field, you'll need to actually go back into the Admin UI and set a group for your user *before* added the `isAccessAllowed` access control. When I tried that, I got no error.

*However*, it looks like there's still an issue. The `userGroup` relationship isn't resolved in the passed object, so you just get something like this:
```js
{
  name: 'Admin',
  email: 'admin@keystone.js',
  isAdmin: true,
  password: '$2b$10$YYPVI9OZ0U6t89/AONfG8OMRna5T.HDChOMY31//pF/2hxh.umdgm',
  __v: 0,
  userGroup: 5e7314291a225375e0ee768a,
  id: '5de0812443f6726604975c0c'
}
```

thought which you cannot access the properties of the `Group` list... 🤔 

This will require some thought.

**Comment by HackerYunen** [comment]
Yes, you are right. 
After I add a UserGroup data for the admin user, this TypeError was gone, but I still can use it to login in.
Meybe just as you said`The userGroup relationship isn't resolved in the passed object`?

**Comment by Vultraz** [comment]
Yes. In my testing the `userGroup` field only gives you the ID of the `Group` entry, not the actual group data.

Pinging @MadeByMike since he added the `isAccessAllowed` feature.

**Comment by HackerYunen** [comment]
Not only in login function, but also in the field access control. 
Like:
```
const userCanVerify = ({
    authentication: {
      item: user
    }
  }) =>
  Boolean(user && user.userGroup.enableVerifyDoc);
```
Horrible bug, it made a mess for my authority control. 😫

**Comment by MadeByMike** [comment]
I'm not exactly sure what the bug is here. It's a known "feature" that we only return the ID for related items in access control. The reason for this is the list can be HUGE and in large systems generating queries to resolve all those items is going to take a long time. 

If we populated those items should we then resolve all the relations at this level? If the assumption is yes we could end up with a situation where we are fetching the entire database and solving problems with circular references.

The solution is to fetch the id and make a 2nd query with `keystone.executeQuery` if required.

**Comment by MadeByMike** [comment]
In this specific case I'm not sure if that's the issue, `user.userGroup` should contain an array of `id`s or be `undefined` if the relationship is not set. I think all of this is expected behaviour.
