### ISSUE TITLE
Inherited Users can't log in

### ISSUE THREAD

**Issue by autoboxer** [keystonejs/keystone#2561]
In keystone.js, there is a single model listed under 'user model' which can be used to sign in.  In order to get multiple user types on a site, creating a model that inherits from the one listed under 'user model' seems to be the only way, however, there's an issue when inherited users attempt to log in.

When any user attempts to log in the following happens:
1.  there's a call to doSignin(...).  A few checks pass and there's an attempt to get a user of the type 'user model' specified in keystone.js.
2.  There's a call to user._.password.compare(...) on the user object that returns from step 1, which is defined in PasswordType.js.  The compare function runs 'bcrypt.compare(candidate, item.get(this.path), callback);', where candidate is the unencrypted password, and item.get(this.path) is the encrypted password.

This is where we see the difference, bcrypt.compare(..) on the model listed under 'user model' in keystone.js is successful, but bcrypt.compare(...) on the model inheriting from the model listed under 'user model' is not.

It's the same behavior every time too.  When the 60 character password hash created by bcrypt and stored in the user object is compared with the unencrypted password based on bcrypt's logic, they don't match.  There's some complicated behavior at play regarding a salt that is created from the first 30 characters of the encrypted hash in order to process the unencrypted password and make the match.  If a non-inherited model is listed in keystone.js under 'user model', logging in works just fine.

Example model (this would be the one listed in keystone.js under 'user model':

```
var keystone = require('keystone'),
    Types = keystone.Field.Types;

// Create model
var User = new keystone.List('User', {
    track: true,
    map: { name: 'name.last' },
    defaultSort: 'name.last'
});

// Create fields
User.add('General Information', {

    name: {
        first: { type: Types.Text, label: 'first name', required: true, index: true, initial: true },
        last: { type: Types.Text, label: 'last name', required: true, index: true, initial: true }
    },

    password: { type: Types.Password, label: 'password', required: true, initial: true },
    avatar: { type: Types.CloudinaryImage, label: 'avatar', folder: 'users/admin', autoCleanup: true }

    email: { type: Types.Email, label: 'email address', unique: true, required: true, index: true, initial: true },

});

// Provide access to Keystone (simplified for the test)
User.schema.virtual('canAccessKeystone').get(function() {
    'use strict';
    return true;
});

// Define default columns in the admin interface and register the model
User.defaultColumns = 'name.first, name.last, email';
User.register();
```

Example model which inherits from the one listed in keystone.js under 'user model':

```
var keystone = require('keystone'),
    Types = keystone.Field.Types,
    User = keystone.list('User');

// Create model
var TestUser = new keystone.List('TestUser', { inherits: User });

// Create fields
TestUser.add('More Permissions', {

    morePermissions: {
        canPassGo: { type: Boolean, label: 'can pass go', default: false, initial: true },
        canCollect200: { type: Boolean, label: 'can collect $200.00', default: true, initial: true }
    }

});

// Define default columns in the admin interface and register the model
TestUser.defaultColumns = 'name.last, email, canPassGo';
TestUser.register();
```

**Comment by autoboxer** [comment]
My proposed fix for this is a change to PasswordType.js:

```
if(!item.isEncrypted) {
			bcrypt.genSalt(field.workFactor, function(err, salt) {
				if (err) {
					return next(err);
				}
				bcrypt.hash(item.get(field.path), salt, function () {}, function(err, hash) {
					if (err) {
						return next(err);
					}
					// override the cleartext password with the hashed one
					item.set(field.path, hash);
					// inherited models save twice, this ensures the encrypted password hash won't be encrypted a second time
					item.isEncrypted = true;
					next();
				});
			});
		} else {
			return next();
		}
```

My changes involve wrapping the `bcrypt.genSalt(...)` function in an if/else statement to look for whether the password has been encrypted during the current save cycle.  On successful save, I set `item.isEncrypted = true;` to prevent the second pass through the pre-save hook from attempting to encrypt the already encrypted password.  When the model is initially saved, and each time the password is changed, there are two passes through the pre-save hook, in the first, `item.isEncrypted` will evaluate to `undefined`, and after a successful encryption, it will evaluate to `true`, preventing the encrypted password from being overwritten.

Thanks to @webteckie and @snowkeeper for help in solving this problem.

**Comment by JedWatson** [comment]
Should be fixed by the commit I just made to 0.4 (0f8dbcf156bb7a5e84a6272cb7926e34f9aa7a05) - @autoboxer to confirm, and port for 0.3.x

**Comment by adrien-k** [comment]
I have the same issue again with inherited user models on version 4.0.0-beta.4

`schema.pre('save')` is called twice but the second time `this.isModified('password`)` is still true even though `password` already contains the encrypted password; it is then encrypted again. 

I could not figure out the cause yet... any idea ?

**Comment by Noviny** [comment]
Just tested this using the example provided by autoboxer, and it is currently working (beta 5). @adrien-k, can you provide any extra information?

**Comment by adrien-k** [comment]
@Noviny I'll try again with beta 5 and provide an example if I isolate the error.

**Comment by adrien-k** [comment]
@Noviny I'm still having the issue with keystone@4.0.0-beta.5, here is an isolated test case : 
```
const keystone = require('keystone');

keystone.init({
  name: 'test',
  'cookie secret': 'topsecret',
});
const Types = keystone.Field.Types;

const BaseUser = new keystone.List('BaseUser');
BaseUser.add(
  {
    password: Types.Password,
  }
);
BaseUser.register();

const User = new keystone.List('User', { inherits: BaseUser });
User.register();

keystone.start();

keystone.list('User').model.create({ password: 'test' })
.then((user) => {
  user._.password.compare('test', (err, isMatch) => {
    console.log('password match result: ' + isMatch);
    process.exit(0);
  });
});
```

**Comment by Noviny** [comment]
@adrien-k thanks a lot for the really clear code example. Confirmed that this was not working on beta-5, however as soon as I jumped to the master branch, this passed. It looks like this has been incidentally solved somewhere. I'd recommend pinning a project to the current commit until we cut a new branch if this is blocking you.

**Comment by rafaneri** [comment]
4.0.0-beta.7 same problem.

**Comment by autoboxer** [comment]
@rafaneri, are you able to update to the master branch?  It's working for me there.

**Comment by rafaneri** [comment]
thanks @autoboxer, it works fine!
