### ISSUE TITLE
0.4: DateTime e2e tests fail

### ISSUE THREAD

**Issue by webteckie** [keystonejs/keystone#3330]
### Steps to reproduce the behavior
1. Edit test/e2e/adminUI/tests/group005Fields/testDatetimeField.js as follows:

    change `'@disabled': true` to `'@disabled': false`

2. Run the test:  

    `node test/e2e/server.js --env default --config test/e2e/adminUI/nightwatch.json --test test/e2e/adminUI/tests/group005Fields/testDatetimeField`

### Expected behavior
The test should pass.
### Actual behavior
The test fails.

NOTE:  once the test passes please leave it enabled!

**Comment by jstockwin** [comment]
I noticed this a while ago too, I bought it up in slack but didn't create an issue for some reason. Anyway, here's a little more info:

To reproduce, start test server and create a new datetime. Paste in 2016-01-01 as the date and 12:00:00 am as the time. Add a name and click save. You'll get an error: `FieldA is invalid`.

Interestingly, if you click the `now` button first, but then overwrite the filled values with the above, it works. Very strange.

**Comment by Noviny** [comment]
@jstockwin doing triage Wondering if this has been fixed, or is still an issue?

**Comment by jstockwin** [comment]
@Noviny I don't remember this being fixed, however the test that @webteckie mentions in this issue has been enabled again ([this line](https://github.com/keystonejs/keystone/blob/master/test/e2e/adminUI/tests/group006Fields/testDatetimeField.js#L5) is commented out, which was done in [this refactoring commit](https://github.com/keystonejs/keystone/commit/2509d4199a728d1b91c4a9c38ce9d92c30b7e7f8)).

It might just be that the new way of doing the tests doesn't quite trigger this bug, or it may have been fixed - not sure. @webteckie might remember?

**Comment by epihacker** [comment]
@jstockwin @Noviny  the test most likely still fails.  It may be working because there's a bunch of test code commented out.  Need to revisit/uncomment the code to see what's going on.
